# Generated by Django 5.0.4 on 2024-10-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_mobile_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
